# -*- coding: utf-8 -*-
"""ImageNet_Classification.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xuP-5pG9iP_WCylDDzS4oIwn1G7hunUz
"""

import tensorflow
from tensorflow.keras.applications import VGG19
import h5py

model = VGG19(weights = 'imagenet')

model.summary()

model.save("imagenet.h5")

